import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'node:path';

// Library mode build:
//   - ESM:  dist/index.js
//   - CJS:  dist/index.cjs
//   - DTS:  dist/index.d.ts  (generated by `tsc --emitDeclarationOnly`)
//
// React + react-dom are marked external so consumers bring their own.
export default defineConfig({
  plugins: [react()],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      formats: ['es', 'cjs'],
      fileName: (format) => (format === 'es' ? 'index.js' : 'index.cjs'),
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
      },
    },
    sourcemap: true,
    minify: false,
    target: 'es2020',
  },
});
