import StyleDictionary from 'style-dictionary';
import fs from 'node:fs';

const T = './src/tokens';
const nameSet = (f) => new Set(Object.keys(JSON.parse(fs.readFileSync(`${T}/${f}`))));
const legacyNames = nameSet('legacy.json');
const darkNames   = nameSet('semantic.dark.json');

// name = the flat DTCG key verbatim (already the full ps-... custom-property stem)
StyleDictionary.registerTransform({
  name: 'ps/name', type: 'name',
  transform: (t) => t.path.join('-'),
});

const base = {
  usesDtcg: true,
  transform: { 'ps/name': undefined }, // placeholder, set below
};

function sd(sources, platform) {
  return new StyleDictionary({
    usesDtcg: true,
    source: sources,
    platforms: { css: platform },
  });
}

const CSS = (opts) => ({
  transforms: ['ps/name'],
  buildPath: './build/',
  files: [opts],
});

// 1) main :root — primitive + semantic(light) + component
await (await sd(
  [`${T}/primitive.json`, `${T}/semantic.json`, `${T}/component.json`],
  CSS({ destination: 'root.css', format: 'css/variables',
        options: { selector: ':root', outputReferences: true } })
)).buildAllPlatforms();

// 2) legacy aliases :root  (all sources present so refs resolve; output only legacy)
await (await sd(
  [`${T}/primitive.json`, `${T}/semantic.json`, `${T}/component.json`, `${T}/legacy.json`],
  CSS({ destination: 'legacy.css', format: 'css/variables',
        filter: (t) => legacyNames.has(t.path.join('-')),
        options: { selector: ':root', outputReferences: true } })
)).buildAllPlatforms();

// 3) dark overrides (semantic.dark wins over semantic for same keys; output only dark)
await (await sd(
  [`${T}/primitive.json`, `${T}/semantic.json`, `${T}/component.json`, `${T}/semantic.dark.json`],
  CSS({ destination: 'dark.css', format: 'css/variables',
        filter: (t) => darkNames.has(t.path.join('-')),
        options: { selector: '[data-theme="dark"]', outputReferences: true } })
)).buildAllPlatforms();

// assemble one tokens.css
const header = `/* ================================================================
   PartsSource Design System — Token Sheet  (GENERATED)
   Regenerated by Style Dictionary v4 from src/tokens/*.json
   Source of truth reverse-engineered from tokens.css v1.2.0.
   DO NOT EDIT BY HAND — edit the DTCG source and rebuild.
   ================================================================ */
`;
const read = (f) => fs.readFileSync(`./build/${f}`, 'utf8');
fs.writeFileSync('./build/tokens.css',
  header + '\n' + read('root.css') + '\n' + read('legacy.css') + '\n' + read('dark.css'));
console.log('built ./build/tokens.css');
