/**
 * Regenerate tokens.css from the DTCG source in /tokens using Style Dictionary v4.
 * Source of truth = tokens/*.json.  Output = tokens.css (repo root) by default,
 * or the path passed as argv[2] (used by the gate to build to a temp file).
 *
 *   npm run build:tokens            # writes ./tokens.css
 *   node scripts/build-tokens.mjs /tmp/out.css
 */
import StyleDictionary from 'style-dictionary';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const OUT = process.argv[2] || 'tokens.css';
const T = new URL('../tokens/', import.meta.url).pathname;
const nameSet = (f) => new Set(Object.keys(JSON.parse(fs.readFileSync(path.join(T, f)))));
const legacyNames = nameSet('legacy.json');
const darkNames   = nameSet('semantic.dark.json');

// Root sheet sets are sourced dynamically from tokens/$metadata.json so that any
// new token set (e.g. an "Email Template" set pushed from Tokens Studio) flows
// into tokens.css automatically. `legacy` and `semantic.dark` are excluded here —
// they keep their own filtered outputs below (legacy.css / dark.css).
const meta = JSON.parse(fs.readFileSync(path.join(T, '$metadata.json'), 'utf8'));
const EXCLUDE = new Set(['legacy', 'semantic.dark']);
const rootSets = (meta.tokenSetOrder || [])
  .filter((s) => !EXCLUDE.has(s))
  .map((s) => `${s}.json`)
  .filter((f) => fs.existsSync(path.join(T, f)));

StyleDictionary.registerTransform({
  name: 'ps/name', type: 'name', transform: (t) => t.path.join('-'),
});

const work = fs.mkdtempSync(path.join(os.tmpdir(), 'ps-tokens-'));
const sd = (sources, file) => new StyleDictionary({
  usesDtcg: true,
  log: { warnings: 'disabled', verbosity: 'silent' },
  source: sources,
  platforms: { css: { transforms: ['ps/name'], buildPath: work + '/', files: [file] } },
});
const F = (dest, opts) => ({ destination: dest, format: 'css/variables', ...opts });

await (await sd(
  rootSets.map((f)=>path.join(T,f)),
  F('root.css', { options: { selector: ':root', outputReferences: true } })
)).buildAllPlatforms();

await (await sd(
  ['primitive.json','semantic.json','component.json','legacy.json'].map((f)=>path.join(T,f)),
  F('legacy.css', { filter: (t)=>legacyNames.has(t.path.join('-')),
    options: { selector: ':root', outputReferences: true } })
)).buildAllPlatforms();

await (await sd(
  ['primitive.json','semantic.json','component.json','semantic.dark.json'].map((f)=>path.join(T,f)),
  F('dark.css', { filter: (t)=>darkNames.has(t.path.join('-')),
    options: { selector: '[data-theme="dark"]', outputReferences: true } })
)).buildAllPlatforms();

const header = `/* ================================================================
   PartsSource Design System — Token Sheet  (GENERATED)
   Regenerated by Style Dictionary v4 from /tokens/*.json
   DO NOT EDIT BY HAND — edit the DTCG source in /tokens and run
   \`npm run build:tokens\`.  CI (\`npm run test:tokens\`) fails if this
   file drifts from the source.
   ================================================================ */
`;
const r = (f) => fs.readFileSync(path.join(work, f), 'utf8');
fs.writeFileSync(OUT, header + '\n' + r('root.css') + '\n' + r('legacy.css') + '\n' + r('dark.css'));
fs.rmSync(work, { recursive: true, force: true });
console.log('build:tokens → wrote', OUT);
